repositories:
  - url: https://github.com/olegsl2011/GoiT-DevOps-Project.git
    name: django-helm

applications:
  - name: django-app
    project: default
    repoURL: https://github.com/olegsl2011/GoiT-DevOps-Project.git
    path: charts/django-app
    targetRevision: lesson-8-9
    server: https://kubernetes.default.svc
    namespace: django
    image:
    repository: "908061117191.dkr.ecr.us-west-2.amazonaws.com/goit-devops-project-ecr"
    pullPolicy: IfNotPresent
    tag: "v1"
    helm:
      valueFiles:
        - values.yaml
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true