{{- range .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  project: {{ .project | default "default" | quote }}
  source:
    repoURL: {{ .repoURL | quote }}
    path: {{ .path | quote }}
    targetRevision: {{ .targetRevision | default "HEAD" | quote }}
    helm:
      valueFiles:
{{- range .helm.valueFiles }}
        - {{ . | quote }}
{{- end }}
  destination:
    server: {{ .server | quote }}
    namespace: {{ .namespace | quote }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}